#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.
xrandr --dpi 102		# Set DPI. User may want to use a larger number for larger screens.
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup

autostart="compfy mpd keynav dunst transmission-daemon unclutter pipewire remapd notifysong"

for program in $autostart; do
	pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

syncthing --no-browser >/dev/null &

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
